version: "3.7"
volumes:
  dash-data:
    external: true
services:
  react:
    image: node:latest
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./react-folder/attendees:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - NODE_ENV=development
    ports:
      - "3001:3001"
  database:
    image: postgres:14.2-bullseye
    volumes:
      - dash-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=gigagraph
      - POSTGRES_PASSWORD=dash
    ports:
      - 15432:5432
  gigagraph:
    build:
      context: ./gigagraph
      dockerfile: ./dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./gigagraph:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://gigagraph:password@database:5432/gigagraph"
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      DJWTO_SIGNING_KEY: ${DJWTO_SIGNING_KEY}
  web:
    image: nginx
    volumes:
      - ./react-folder:/usr/share/nginx/html:ro
    ports:
      - "3000:80"