# Generated by Django 4.0.5 on 2022-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('data_sent', models.FloatField()),
                ('data_received', models.FloatField()),
                ('data_total', models.FloatField()),
            ],
        ),
    ]
