# Generated by Django 4.0.3 on 2022-07-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyData',
            new_name='SessionData',
        ),
    ]
