# Generated by Django 4.0.3 on 2022-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0002_rename_dailydata_sessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='session_time',
            field=models.IntegerField(null=True),
        ),
    ]
